<?php

use Illuminate\Database\Seeder;

class DesignationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       DB::table('designations')->insert([
        	['designation_name' => ' Supervisor', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
        	['designation_name' => 'Assistant  Supervisor', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
        	['designation_name' => 'Analyst-Business Analytics', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Analyst-Consulting and Technology', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Analyst-Solutions Design', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Business Development', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Compliances', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Customer Support', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Distributions', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Finance & Accounts', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Fulfillment Operations', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Internal Communication', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Operation Development', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Operations', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Payroll', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Procurement', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Transportation', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Assistant Manager-Vertical Development-South', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Associate Director-Retail', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Associate Software Enginneer', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Business Development', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Cash  Collection Executive', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Checker', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Computer Operator', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Consulting', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Controller Finnace & Accounts', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Corporate  Recuriter', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'CRM', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Customer Service Executive', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Data Entry Operator', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Delivery Boy', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Design Engineer', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Director', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Director-Finance', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Etf Operator', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Etf Supervisor', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Executive', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'F2B OPER', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Floor Executive', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Floor Supervisor', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Forklift Driver', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Forklift Operator', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Front Office Executive', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'GET', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head Business Development', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head Design', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head Operations India', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head-Communication', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head-Finance and Accounts', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head-Fulfilment Operations-India Corporate', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head-IT Development & Database Management', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head-Operations-South', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head-PAS Engineering', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head-Supply Chain & Implementation', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head-Vertical Development', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Head-Vertical Development (F& L)', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Helper', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'High Steaker', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Housekeeping Staff', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'IT Infra Manager', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Junior Supervisor', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Labour', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead – Operations Development', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead Operations Corporate', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead Operations North', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead Operations South', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead Operations West', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead Transportation North', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Admin', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Business Development', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Compliances', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Continuous Improvement-Coimbatore', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Customer Support', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Distribution', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Fulfillment Operations', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Graphic & Web Designing', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-IT Development & Database Management', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Operations', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Lead-Quality Assurance', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Loading Suppervisor', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'M.C Operater ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Operations ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager Solution Design ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager Transportation ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Business Analytics ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Business Development ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Distribution-East ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Distribution-West ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Distribution-North ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Distribution-South ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-FC ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Finance & Accounts  ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Operations Excellence  ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Manager-Vertical Development-West  ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'MHE ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'MIS ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Network Engineer-IT Infrastructure Support & Network Admin  ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Office Boy ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Operation Support  ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Operations Executive  ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Picker & Packer ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Quality Executive ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Registration Desk Executive ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Senior Executive ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Senior Manager-Customer Relationship', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Senior Manager-Distribution', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Senior Officer', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Senior Software Engineer-IT Development & Database Management', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Senior System Administrator', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Seniore Execuitve', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Site Executive', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Site Incharge', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Site Manager', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Software Engineer-IT Development & Database Management', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Solution Designer', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Specialist', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Store Assistant ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Store Incharge ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Support Executive ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'System Administrator ', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Telecaller', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Vna Operator', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Warehouse Executive', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
            ['designation_name' => 'Warehouse Incharge', 'department_id' => '1', 'created_at' => date('Y-m-d H:i:s')],
        ]);
    }
}
